### ISSUE TITLE
[arcface_torch]arcface pytorch training is working ok with 2 gpus , but failed at 4 gpus by my setting , details shown below

### ISSUE THREAD

**Issue by leoluopy** [deepinsight/insightface#1435]
while i trained the arcface pytorch with 2 gpus , which used the command below , it worked fine :
`python -m torch.distributed.launch --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=1234 train.py`

but failed by set the nproc_per_node=4 , my command is :
`python -m torch.distributed.launch --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=1234 train.py`

the error is:
```
  File "train.py", line 135, in <module>
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    main(args_)
  File "train.py", line 26, in main
    rank=args.local_rank)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    main(args_)
  File "train.py", line 26, in main
    rank=args.local_rank)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    main(args_)
  File "train.py", line 26, in main
    rank=args.local_rank)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=3']' returned non-zero exit status 1.
```

@anxiangsir do you have any idea ? great thanks  !

**Comment by leoluopy** [comment]
my machine has 4 gpus : 2080 ti

**Comment by leoluopy** [comment]
i have tried the command below , but it's still not working : 
```
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/bin/python -m torch.distributed.launch --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=1234 train.py

NCCL_SOCKET_IFNAME=eth0 NCCL_IB_DISABLE=1 /opt/conda/bin/python -m torch.distributed.launch --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=1234 train.py
```

**Comment by anxiangsir** [comment]
Have you tried to change the port？

**Comment by leoluopy** [comment]
@anxiangsir thanks for reply in such a short time . the problem is solved  by changing the pytorch version to 1.6.0

**Comment by anxiangsir** [comment]
torch 1.7.1 is better for fp16

**Comment by leoluopy** [comment]
> torch 1.7.1 is better for fp16

in my situation , the problem occurred right at the version of 1.7.1 , i  tried 1.7.0 , it's not working as well . maybe in the future as i have time , try to find the deeper reason

**Comment by anxiangsir** [comment]
2333, waiting for your reply
