### ISSUE TITLE
[arcface_torch]training arch_face torch failed when using multi-nodes

### ISSUE THREAD

**Issue by leoluopy** [deepinsight/insightface#1444]
i have two machines and trained the arcface in distributed way . but errors occurred at my second machine then the master node blocked . the error is below:

```
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main(args_)
  File "train.py", line 63, in main
    dist.broadcast(ps, 0)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 842, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8
```

any ideas ? @anxiangsir

**Comment by leoluopy** [comment]
this  issue is solved . here are the tips for all who may meet it in the future.
### reason:
my training environment is in docker . but the ip addr of the docker address is separated from the physical machines , whereby using the nccl backend will not gain the right ip addr for communicating .
### work around strategy :
i changed my docker starting command and modified the network mode as host shared mode where the docker container will shared the whole network environment with the host machine . maybe it's not safe , but who will be interested for hacking me ? 
`sudo nvidia-docker run -it  --network=host --privileged -v /dev/mem:/dev/mem -v /home/:/data  -v /etc/localtime:/etc/localtime   --restart=always wisesoft:pytorch  /bin/bash -c  " /bin/bash"  `

**Comment by anxiangsir** [comment]
nice!
