### ISSUE TITLE
mxnet.base.MXNetError: [09:20:39] src/operator/nn/./cudnn/cudnn_convolution-inl.h:683: Check failed: e == CUDNN_STATUS_SUCCESS (4 vs. 0) : cuDNN: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by DongzhongZheng** [deepinsight/insightface#1449]
![2021-03-31 172251](https://user-images.githubusercontent.com/44435640/113123044-cbd48280-9246-11eb-8067-5f3a62bc2861.png)

when I run insightface-master/detection/RetinaFace/test.py with GPU, I got this error message, How do I deal with this problem? Thanks.

**Comment by vodanhbk95** [comment]
if you wanna run with GPU, please install mxnet with cuda suitable version
In my case, my system is cuda10.2 so I install "pip install mxnet-cu102mkl" and it worked.
If your cuda version is not the same with me, just install "pip install mxnet-{cuda_version}mkl". Hope it help

**Comment by michellerybak** [comment]
installing cuda 11.3 and mxnet-cu113 and cudnn 8 fixed this for me
