### ISSUE TITLE
[arcface_torch] Problems with distributed training in arcface_torch

### ISSUE THREAD

**Issue by luisfmnunes** [deepinsight/insightface#1905]
Good Afternoon, 

I have a current setup of two machines in the same network, each of them presenting a RTX3090 GPU, and despite intializing a process in each of the machines (Checked with nvidia-smi), and the master machine printing "Training YYYY-MM-DD HH:MM:SS,MS-rank_id: 0" both processes seem to freeze (power usage decay on GPUs) and later on the following error is raised in the master machine:

```
python_env/lib64/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun.                                                                                                                
Note that --use_env is set by default in torchrun.                                                                                                                          
If your script expects `--local_rank` argument to be set, please                                                                                                             
change it to read from `os.environ['LOCAL_RANK']` instead. See                                                                                                               
https://pytorch.org/docs/stable/distributed.html#launch-utility for                                                                                                          
further instructions                                                                                                                                                         
                                                                                                                                                                             
  FutureWarning,                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                           
  File "train.py", line 141, in <module>                                                                                                                                     
    main(parser.parse_args())                                                                                                                                                
  File "train.py", line 59, in main                                                                                                                                          
    module=backbone, broadcast_buffers=False, device_ids=[local_rank])                                                                                                       
  File "/home/nunes/python_env/lib64/python3.6/site-packages/torch/nn/parallel/distributed.py", line 578, in __init__                                                        
    dist._verify_model_across_ranks(self.process_group, parameters)                                                                                                          
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled system error, NCCL version 21.0.3                                            
ncclSystemError: System call (socket, malloc, munmap, etc) failed.                                                                                                           
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 123541) of binary: /home/nunes/python_env/bin/python
```

Both machines present the same NCCL (21.0.3) and Driver Versions (510.47.03).
(Fun fact, swapping the ranks and the master machine, the error still pop on the same machine, implying the problem is with such machine.)

These are my running configurations:

Master (Machine 1) - Rank 0
```bash
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr="192.168.0.207" --master_port=1234 train.py configs/test_02
ps -ef | grep "train" | grep -v grep | awk '{print "kill -9 "$2}' | sh
```

Machine 2 - Rank 1
```bash
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="192.168.0.207" --master_port=1234 train.py configs/test_02
ps -ef | grep "train" | grep -v grep | awk '{print "kill -9 "$2}' | sh
``` 

Any ideas what might be the cause of this problem?

-----------------------------------------------------------------------------------------------------------------------------------------------------------
Edit:

Okay, so I enabled NCCL Debug with `export NCCL_DEBUG=INFO` and seems like it is a NCCL connection problem according to this output:

```
FutureWarning,
gr3090:166652:166652 [0] NCCL INFO Bootstrap : Using enp6s0:192.168.0.136<0>
gr3090:166652:166652 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gr3090:166652:166652 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
gr3090:166652:166652 [0] NCCL INFO NET/Socket : Using [0]enp6s0:192.168.0.136<0>
gr3090:166652:166652 [0] NCCL INFO Using network Socket
gr3090:166652:166738 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
gr3090:166652:166738 [0] NCCL INFO Channel 00 : 0[1000] -> 1[9000] [receive] via NET/Socket/0
gr3090:166652:166738 [0] NCCL INFO Channel 01 : 0[1000] -> 1[9000] [receive] via NET/Socket/0
gr3090:166652:166738 [0] NCCL INFO Channel 00 : 1[9000] -> 0[1000] [send] via NET/Socket/0
gr3090:166652:166738 [0] NCCL INFO Channel 01 : 1[9000] -> 0[1000] [send] via NET/Socket/0
gr3090:166652:166738 [0] NCCL INFO Call to connect returned Connection timed out, retrying
gr3090:166652:166738 [0] NCCL INFO Call to connect returned Connection timed out, retrying

gr3090:166652:166738 [0] include/socket.h:409 NCCL WARN Net : Connect to 192.168.122.1<49891> failed : Connection timed out
gr3090:166652:166738 [0] NCCL INFO transport/net_socket.cc:316 -> 2
gr3090:166652:166738 [0] NCCL INFO include/net.h:21 -> 2
gr3090:166652:166738 [0] NCCL INFO transport/net.cc:210 -> 2
gr3090:166652:166738 [0] NCCL INFO transport.cc:111 -> 2
gr3090:166652:166738 [0] NCCL INFO init.cc:778 -> 2
gr3090:166652:166738 [0] NCCL INFO init.cc:904 -> 2
gr3090:166652:166738 [0] NCCL INFO group.cc:72 -> 2 [Async thread]
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main(parser.parse_args())
  File "train.py", line 59, in main
    module=backbone, broadcast_buffers=False, device_ids=[local_rank])
  File "/home/nunes/penv/lib64/python3.6/site-packages/torch/nn/parallel/distributed.py", line 578, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 166652) of binary: /home/nunes/penv/bin/python
```

**Comment by luisfmnunes** [comment]
OK, problem solved. The catch was one of the machines had a virtual branch (virbr0) and by default NCCL was creating a socket for this branch which provided no response and so would eventually time out. In case you have a similar issua I advise you checking out [How to set NCCL_SOCKET_IFNAME](https://github.com/NVIDIA/nccl/issues/286).

Now the training is running, although not yet normaly, since a single machine was taking around 34 hours to train a R18 backbone model, and the distributed between 2 identical machines is estimating 1241 hours to conclusion.

**Comment by luisfmnunes** [comment]
Just exposing my experience so far. the bottleneck between the distributed training on 2> nodes was the Network, after using a 10 gigabit interface the result observed was completely different.
